### ISSUE TITLE
Evaluate and cleanup configuring the certificates of custom Image repository through environment variables

### ISSUE THREAD

**Issue by prkalle** [vmware-tanzu/tanzu-cli#12]
**Describe the feature request**
This issue is to evaluate and cleanup the process of configuring the certificates of custom image reposity used by CLI.

Currently the below enviroment variables are used to configure certificates of custom image repository
PROXY_CA_CERT
TKG_PROXY_CA_CERT
TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE
TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY

We need to evaluate the option of configuring the certs for each discoverySource in config file as shown below instead of configuring through the environmnet variables.

```
clientOptions:
    cli:
        bomRepo: projects.registry.vmware.com/tkg
        compatibilityFilePath: tkg-compatibility
        discoverySources:
            - local:
                name: default
                path: standalone
                caCerts:  xxxxxx
                skipTLSVerify: false
              contextType: k8s
```
**Describe alternative(s) you've considered**

**Additional context**

**Comment by prkalle** [comment]
Support for cert configuration for given endpoint is provided in the configuration as below
```
certs:
    - hostName: localhost:9876
      caCertData: <REDACTED>
      skipCertVerify: "true"
```

Also new commands to provide CRUD operations was also added. So the below command would be added
`tanzu config cert add --hostname test.host.com --ca-certificate path/to/ca --skip-cert-verify false --insecure false`
`tanzu config cert update test.host.com --ca-certificate path/to/ca --skip-cert-verify false --insecure false`
`tanzu config cert delete test.host.com `
`tanzu config cert list`

Core CLI would use this configuration while interacting with central repository. If there is an entry for central repository endpoint in the cert configuration , the cert configuration would be used

Also, this should enable the plugin developers to use this configuration for thier plugins( tanzu-plugin-runtime repository provides the APIs necessary for Cert config CRUD operations
